[package]
name = "fuzz"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
fuzzed_runtime = {path = "../runtime", package = "frontier-template-runtime"}
ziggy = { version = "1.3.2", default-features = false }
sp-runtime = { workspace = true }
pallet-balances = {workspace = true}
frame-system = {workspace = true}
sp-core = { workspace = true }
sp-state-machine = {workspace = true}
sp-consensus-aura = {workspace = true}
arbitrary = { version = "1.4.1", features = ["derive"] }
evm = { workspace = true }
pallet-evm = { workspace = true }
hex.workspace = true
[features]
fuzzing = []
default = ["std"]
std = ["fuzzed_runtime/std", 
	   "sp-runtime/std", 
	   "sp-state-machine/std", 
	   "sp-consensus-aura/std", 
	   "sp-core/std", 
	   "pallet-evm/std"
]
